INFO 2024-05-18 17:53:22,353 autoreload 784 3080Watching for file changes with StatReloader
INFO 2024-05-18 17:53:27,495 basehttp 784 12036"GET /number/ HTTP/1.1" 200 2
INFO 2024-05-18 18:00:07,331 autoreload 784 3080C:\_GB_django\sem01\sem01\settings.py changed, reloading.
INFO 2024-05-18 18:00:08,008 autoreload 7768 8624Watching for file changes with StatReloader
INFO 2024-05-18 18:00:09,649 autoreload 7768 8624C:\_GB_django\sem01\sem01\settings.py changed, reloading.
INFO 2024-05-18 18:00:10,393 autoreload 6360 2436Watching for file changes with StatReloader
INFO 2024-05-19 15:36:08,997 autoreload 9412 8364Watching for file changes with StatReloader
INFO 2024-05-19 15:36:12,076 basehttp 9412 2608"GET / HTTP/1.1" 200 12
WARNING 2024-05-19 15:36:12,205 log 9412 2608Not Found: /favicon.ico
WARNING 2024-05-19 15:36:12,205 basehttp 9412 2608"GET /favicon.ico HTTP/1.1" 404 3101
INFO 2024-05-19 15:36:17,167 basehttp 9412 2608"GET /game HTTP/1.1" 301 0
ERROR 2024-05-19 15:36:17,257 log 9412 9308Internal Server Error: /game/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 26, in game
    game = Game(side=random.choice['orel','reshka'])
                    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2024-05-19 15:36:17,261 basehttp 9412 9308"GET /game/ HTTP/1.1" 500 63326
INFO 2024-05-19 15:37:11,974 autoreload 9412 8364C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:37:12,658 autoreload 4648 12680Watching for file changes with StatReloader
INFO 2024-05-19 15:37:27,822 autoreload 4648 12680C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:37:28,506 autoreload 4060 12196Watching for file changes with StatReloader
ERROR 2024-05-19 15:37:30,271 log 4060 8136Internal Server Error: /game/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 26, in game
    game = Game(side=random.choice['orel','reshka'])
                    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2024-05-19 15:37:30,274 basehttp 4060 8136"GET /game/ HTTP/1.1" 500 63463
INFO 2024-05-19 15:38:10,168 autoreload 4060 12196C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 15:38:10,807 autoreload 9080 8036Watching for file changes with StatReloader
INFO 2024-05-19 15:39:38,160 autoreload 9080 8036C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:39:38,831 autoreload 8104 10456Watching for file changes with StatReloader
ERROR 2024-05-19 15:39:40,917 log 8104 13484Internal Server Error: /game/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 26, in game
    game = Game(side=random.choice(['orel','reshka']))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\base.py", line 567, in __init__
    raise TypeError(
TypeError: Game() got unexpected keyword arguments: 'side'
ERROR 2024-05-19 15:39:40,922 basehttp 8104 13484"GET /game/ HTTP/1.1" 500 70220
INFO 2024-05-19 15:39:58,604 autoreload 8104 10456C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:39:59,252 autoreload 9720 9476Watching for file changes with StatReloader
INFO 2024-05-19 15:40:12,337 autoreload 9720 9476C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:40:12,961 autoreload 4176 11024Watching for file changes with StatReloader
INFO 2024-05-19 15:40:22,904 autoreload 4176 11024C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:40:23,592 autoreload 12596 1936Watching for file changes with StatReloader
INFO 2024-05-19 15:40:25,170 basehttp 12596 5836"GET /game/ HTTP/1.1" 200 6
INFO 2024-05-19 15:40:27,793 basehttp 12596 5836"GET /game/ HTTP/1.1" 200 6
INFO 2024-05-19 15:40:28,356 basehttp 12596 5836"GET /game/ HTTP/1.1" 200 4
INFO 2024-05-19 15:40:28,857 basehttp 12596 5836"GET /game/ HTTP/1.1" 200 4
INFO 2024-05-19 15:40:29,224 basehttp 12596 5836"GET /game/ HTTP/1.1" 200 6
INFO 2024-05-19 15:41:01,185 autoreload 12596 1936C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:41:01,880 autoreload 9036 9076Watching for file changes with StatReloader
INFO 2024-05-19 15:45:29,063 autoreload 9036 9076C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 15:45:29,730 autoreload 11344 3172Watching for file changes with StatReloader
INFO 2024-05-19 15:46:06,906 autoreload 11344 3172C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 15:46:07,573 autoreload 7704 3128Watching for file changes with StatReloader
INFO 2024-05-19 15:46:30,213 autoreload 7704 3128C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 15:46:30,857 autoreload 12680 4408Watching for file changes with StatReloader
INFO 2024-05-19 15:46:31,580 basehttp 12680 11544"GET /game/ HTTP/1.1" 200 4
INFO 2024-05-19 15:46:32,778 basehttp 12680 11544"GET /game/ HTTP/1.1" 200 6
INFO 2024-05-19 15:46:45,106 autoreload 12680 4408C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:46:45,772 autoreload 13760 5820Watching for file changes with StatReloader
INFO 2024-05-19 15:46:46,611 basehttp 13760 1880"GET /game/ HTTP/1.1" 200 53
INFO 2024-05-19 15:46:49,113 basehttp 13760 1880"GET /game/ HTTP/1.1" 200 51
INFO 2024-05-19 15:46:57,535 basehttp 13760 1880"GET /game/ HTTP/1.1" 200 51
INFO 2024-05-19 15:46:58,155 basehttp 13760 1880"GET /game/ HTTP/1.1" 200 51
INFO 2024-05-19 15:46:58,734 basehttp 13760 1880"GET /game/ HTTP/1.1" 200 53
INFO 2024-05-19 15:46:59,320 basehttp 13760 1880"GET /game/ HTTP/1.1" 200 51
INFO 2024-05-19 15:49:25,834 autoreload 13760 5820C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:49:26,578 autoreload 3732 11908Watching for file changes with StatReloader
INFO 2024-05-19 15:49:50,148 autoreload 3732 11908C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:49:50,815 autoreload 11588 4792Watching for file changes with StatReloader
INFO 2024-05-19 15:56:44,409 autoreload 11588 4792C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 15:56:45,086 autoreload 11756 9124Watching for file changes with StatReloader
INFO 2024-05-19 15:57:44,312 autoreload 11756 9124C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 15:57:45,011 autoreload 13188 13040Watching for file changes with StatReloader
INFO 2024-05-19 15:58:20,747 autoreload 13188 13040C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 15:58:21,389 autoreload 3284 10372Watching for file changes with StatReloader
INFO 2024-05-19 15:58:54,398 autoreload 3284 10372C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 15:58:55,105 autoreload 6556 11348Watching for file changes with StatReloader
INFO 2024-05-19 16:00:46,483 autoreload 6556 11348C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 16:00:47,168 autoreload 1908 11304Watching for file changes with StatReloader
INFO 2024-05-19 16:00:48,787 autoreload 1908 11304C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 16:00:49,439 autoreload 3704 7968Watching for file changes with StatReloader
INFO 2024-05-19 16:01:24,585 autoreload 3704 7968C:\_GB_django\sem01\myapp\urls.py changed, reloading.
INFO 2024-05-19 16:01:25,258 autoreload 12552 4208Watching for file changes with StatReloader
INFO 2024-05-19 16:01:31,624 basehttp 12552 13352"GET /statistic HTTP/1.1" 301 0
ERROR 2024-05-19 16:01:31,669 log 12552 1256Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic())
                        ^^^^^^^^^^^^^^^^
TypeError: Game.statistic() missing 1 required positional argument: 'n'
ERROR 2024-05-19 16:01:31,673 basehttp 12552 1256"GET /statistic/ HTTP/1.1" 500 63543
INFO 2024-05-19 16:01:55,348 autoreload 12552 4208C:\_GB_django\sem01\myapp\views.py changed, reloading.
INFO 2024-05-19 16:01:56,025 autoreload 11820 7776Watching for file changes with StatReloader
ERROR 2024-05-19 16:01:57,798 log 11820 4120Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 15, in statistic
    return Game.objects.all[-n:]
           ~~~~~~~~~~~~~~~~^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2024-05-19 16:01:57,802 basehttp 11820 4120"GET /statistic/ HTTP/1.1" 500 67047
INFO 2024-05-19 16:02:54,511 autoreload 11820 7776C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:02:55,180 autoreload 11580 12676Watching for file changes with StatReloader
ERROR 2024-05-19 16:02:58,290 log 11580 13388Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 15, in statistic
    return ','.join(Game.objects.all[-n:])
                    ~~~~~~~~~~~~~~~~^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2024-05-19 16:02:58,294 basehttp 11580 13388"GET /statistic/ HTTP/1.1" 500 67105
ERROR 2024-05-19 16:03:00,418 log 11580 13388Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 15, in statistic
    return ','.join(Game.objects.all[-n:])
                    ~~~~~~~~~~~~~~~~^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2024-05-19 16:03:00,421 basehttp 11580 13388"GET /statistic/ HTTP/1.1" 500 67105
INFO 2024-05-19 16:03:32,680 autoreload 11580 12676C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:03:33,316 autoreload 5672 11824Watching for file changes with StatReloader
INFO 2024-05-19 16:03:34,940 autoreload 5672 11824C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:03:35,520 autoreload 4956 7848Watching for file changes with StatReloader
ERROR 2024-05-19 16:03:41,166 log 4956 3880Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 15, in statistic
    return ','.join(g for g in Game.objects.all[-n:])
                               ~~~~~~~~~~~~~~~~^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2024-05-19 16:03:41,170 basehttp 4956 3880"GET /statistic/ HTTP/1.1" 500 67157
ERROR 2024-05-19 16:03:42,852 log 4956 3880Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 15, in statistic
    return ','.join(g for g in Game.objects.all[-n:])
                               ~~~~~~~~~~~~~~~~^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2024-05-19 16:03:42,856 basehttp 4956 3880"GET /statistic/ HTTP/1.1" 500 67157
ERROR 2024-05-19 16:03:43,164 log 4956 3880Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 15, in statistic
    return ','.join(g for g in Game.objects.all[-n:])
                               ~~~~~~~~~~~~~~~~^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2024-05-19 16:03:43,167 basehttp 4956 3880"GET /statistic/ HTTP/1.1" 500 67157
INFO 2024-05-19 16:07:26,532 autoreload 4956 7848C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:07:27,233 autoreload 13592 12612Watching for file changes with StatReloader
ERROR 2024-05-19 16:07:28,895 log 13592 9360Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 16, in statistic
    for game in Game.objects.all[-n:]:
           ~~~~~~~~~~~~~~~~^^^^^
TypeError: 'method' object is not subscriptable
ERROR 2024-05-19 16:07:28,899 basehttp 13592 9360"GET /statistic/ HTTP/1.1" 500 67231
INFO 2024-05-19 16:07:44,868 autoreload 13592 12612C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:07:45,555 autoreload 4068 2356Watching for file changes with StatReloader
ERROR 2024-05-19 16:07:46,956 log 4068 9868Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 16, in statistic
    for game in Game.objects.all()[-n:]:
           ~~~~~~~~~~~~~~~~~~^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 431, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2024-05-19 16:07:46,960 basehttp 4068 9868"GET /statistic/ HTTP/1.1" 500 72038
INFO 2024-05-19 16:12:44,694 autoreload 4068 2356C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:12:45,456 autoreload 972 6924Watching for file changes with StatReloader
INFO 2024-05-19 16:13:01,500 autoreload 972 6924C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:13:02,258 autoreload 10416 14048Watching for file changes with StatReloader
ERROR 2024-05-19 16:13:04,545 log 10416 10172Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 18, in statistic
    games=games[-n:]
          ~~~~~^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 431, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2024-05-19 16:13:04,550 basehttp 10416 10172"GET /statistic/ HTTP/1.1" 500 73002
INFO 2024-05-19 16:13:25,379 autoreload 10416 14048C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:13:26,169 autoreload 5288 11232Watching for file changes with StatReloader
ERROR 2024-05-19 16:13:30,226 log 5288 10432Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 18, in statistic
    games=games[:-n]
          ~~~~~^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 431, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2024-05-19 16:13:30,231 basehttp 5288 10432"GET /statistic/ HTTP/1.1" 500 73002
ERROR 2024-05-19 16:13:33,674 log 5288 10432Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 18, in statistic
    games=games[:-n]
          ~~~~~^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 431, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2024-05-19 16:13:33,677 basehttp 5288 10432"GET /statistic/ HTTP/1.1" 500 73002
ERROR 2024-05-19 16:13:35,195 log 5288 10432Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 18, in statistic
    games=games[:-n]
          ~~~~~^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 431, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2024-05-19 16:13:35,199 basehttp 5288 10432"GET /statistic/ HTTP/1.1" 500 73002
INFO 2024-05-19 16:14:05,878 autoreload 5288 11232C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:14:06,617 autoreload 9876 7684Watching for file changes with StatReloader
INFO 2024-05-19 16:14:08,297 autoreload 9876 7684C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:14:09,053 autoreload 13236 11096Watching for file changes with StatReloader
ERROR 2024-05-19 16:14:17,188 log 13236 11104Internal Server Error: /statistic/
Traceback (most recent call last):
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\views.py", line 39, in statistic
    return HttpResponse(Game.statistic(n))
                        ^^^^^^^^^^^^^^^^^
  File "C:\_GB_django\sem01\myapp\models.py", line 18, in statistic
    games=games[:-n]
          ~~~~~^^^^^
  File "C:\Users\01\AppData\Local\Programs\Python\Python312\Lib\site-packages\django\db\models\query.py", line 431, in __getitem__
    raise ValueError("Negative indexing is not supported.")
ValueError: Negative indexing is not supported.
ERROR 2024-05-19 16:14:17,192 basehttp 13236 11104"GET /statistic/ HTTP/1.1" 500 73007
INFO 2024-05-19 16:15:06,015 autoreload 13236 11096C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:15:06,745 autoreload 3416 8316Watching for file changes with StatReloader
INFO 2024-05-19 16:15:10,557 basehttp 3416 5808"GET /statistic/ HTTP/1.1" 200 257
INFO 2024-05-19 16:15:36,124 autoreload 3416 8316C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:15:36,781 autoreload 6420 13424Watching for file changes with StatReloader
INFO 2024-05-19 16:15:38,479 autoreload 6420 13424C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:15:39,297 autoreload 12676 12792Watching for file changes with StatReloader
INFO 2024-05-19 16:15:42,351 basehttp 12676 11144"GET /statistic/ HTTP/1.1" 200 267
INFO 2024-05-19 16:16:03,250 autoreload 12676 12792C:\_GB_django\sem01\myapp\models.py changed, reloading.
INFO 2024-05-19 16:16:03,892 autoreload 2512 1944Watching for file changes with StatReloader
INFO 2024-05-19 16:16:08,995 basehttp 2512 13972"GET /statistic/ HTTP/1.1" 200 257
